### ISSUE TITLE
Ensure all usages of math/big.NewRat never pass in a denominator that is not zero

### ISSUE THREAD

**Issue by odeke-em** [rigelrozanski/rational-test#3]
While wiring this up with go-wire's new JSON codec, I noticed that some spots can pass a 0 into big.NewRat with 0 when say given the zero value
https://github.com/rigelrozanski/rational-test/blob/df87f9a796e5b49a33db2d5757ea246fab6095ab/rational.go#L211

which will panic with

```shell
panic: division by zero [recovered]
	panic: division by zero

goroutine 19 [running]:
testing.tRunner.func1(0xc4201341e0)
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:742 +0x29d
panic(0x129d120, 0x1344000)
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/runtime/panic.go:505 +0x229
math/big.(*Rat).SetFrac64(0xc42009cac0, 0x0, 0x0, 0xc42009aaf0)
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/math/big/rat.go:311 +0xfb
math/big.NewRat(0x0, 0x0, 0xa)
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/math/big/rat.go:25 +0x4f
github.com/rigelrozanski/rational-test.(*Rat).UnmarshalJSON(0xc4200ac100, 0xc420148036, 0xa, 0x8a, 0xc4200ac100, 0x16)
	/Users/emmanuelodeke/go/src/github.com/rigelrozanski/rational-test/rational.go:216 +0xa3
```

**Comment by rigelrozanski** [comment]
Confused why this is a problem? If the denominator is ever 0 it SHOULD panic. If you define a zero constant it makes sense to define as 0/1 ... are you saying that this value 0/1 has a problem when passing through go-wire?

**Comment by odeke-em** [comment]
Am just saying that this program should never panic
```go
package main

import (
	"encoding/json"
	"fmt"

	"github.com/rigelrozanski/rational-test"
)

func main() {
	r1 := new(rational.Rat)
	samples := []string{"{}", `{"numerator": 0, "denominator":0}`}
	for i, sample := range samples {
		if err := json.Unmarshal([]byte(sample), r1); err != nil {
			fmt.Printf("#%d err: %v\nblob: %s\n", i, err, sample)
		}
	}
}
```

**Comment by rigelrozanski** [comment]
Okay agreed yeah I added panic handling/ some tests
